# Generated by Django 5.0 on 2024-01-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usermodel_email_alter_usermodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
