# Generated by Django 5.0 on 2024-01-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_usermodel_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userModel',
        ),
    ]
