# Generated by Django 5.0 on 2024-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_adminmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
